"""Subclass of SwitchFrame, which is generated by wxFormBuilder."""

import wx
import gui


# Implementing SwitchFrame
class SwitchDiscoverSwitchFrame(gui.SwitchFrame):
    def __init__(self, parent):
        gui.SwitchFrame.__init__(self, parent)
